version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo "Initializing environment"
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain devops --domain-owner 406202011526 --region us-east-1 --query authorizationToken --output text)
      - export CODEARTIFACT_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --domain devops --domain-owner 406202011526 --repository Devops_cicd --format maven --region us-east-1 --query repositoryEndpoint --output text)
      - echo "Logging in to CodeArtifact"
      - aws codeartifact login --tool maven --domain devops --domain-owner 406202011526 --repository Devops_cicd --region us-east-1

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn -s settings.xml compile

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - mvn -s settings.xml package

artifacts:
  files:
    - target/devops-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
